### ISSUE TITLE
Only sees 112 movies out of many hundreds

### ISSUE THREAD

**Issue by Stooovie** [billyinferno/jellyfin-countryTagUpdater#45]
Fantastic tool, but in my library, it only sees 112 movies our of almost 2000. Movies being in subfolders is not the issue. Any ideas?

**Comment by billyinferno** [comment]
I already long time not updating the tools, will need to check what is the API call resulted when fetch the library list, because I think Jellyfin already moved to new API.

Might be you can check the API call response on the browser console and see if it fetch the library correctly or not, if not then probably will need to use different API to fetch the library.

**Comment by Stooovie** [comment]
I don't know how to do that with an Electron app, I'm not a dev :-/ thank you for the answer anyway. Maybe someday Jellyfin will add filtering by country natively.

**Comment by Stooovie** [comment]
I updated to Jellyfin 10.9.6 and your app is now fully working! All movies are tagged now. Cool!
